import "./globals.css";
import { Recursive } from "next/font/google";
import Providers from "@/app/components/Providers";

const recursive = Recursive({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="tracking min-h-screen overflow-x-hidden scroll-smooth antialiased"
    >
      <Providers>
        <body
          className={`${recursive.className} flex min-h-screen justify-center from-slate-700`}
        >
          {children}
        </body>
      </Providers>
    </html>
  );
}
